spring.application.name=MiniShop

# ===========================
# Database MySQL
# ===========================
spring.datasource.url=jdbc:mysql://localhost:3306/MiniShop
spring.datasource.username=root
spring.datasource.password=
spring.datasource.driver-class-name=com.mysql.cj.jdbc.Driver

spring.jpa.hibernate.ddl-auto=update
spring.jpa.show-sql=true
spring.jpa.properties.hibernate.dialect=org.hibernate.dialect.MySQLDialect

#config pagination
#start index = 1
spring.data.web.pageable.one-indexed-parameters =true
# default page size 10
spring.data.web.pageable.default-page-size=10

# cloud aws
aws.accessKey=${aws.accessKey}
aws.secretKey=${aws.accessKey}
aws.region=us-east-2
aws.bucketName=mt-minishop-product-images

#config jwt
mt.jwt.base64-secret=qoAEABDke07+AVLepXB4aCMtsT0wMAqR5x2VFyldsnx6e75YQkJH2UcZKTjEyoNgG71SBCXfq5N6NVZxWOfsHQ==
# 100 day
mt.jwt.access-token-validity-in-seconds=86400
mt.jwt.refresh-token-validity-in-seconds=8640000
###